### ISSUE TITLE
Module not found: Error: Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by paul8liveira** [bassarisse/app-up-build#1]
Boa tarde. Utilizamos o app-up-build no PECEGE, gostaria de saber como resolver a dependência do módulo 'fs'. Segue o ocorrido:

Instalei a pacote do google translate @google-cloud/translate, fazendo a requisição dele em qualquer local ocorre erro no start da aplicação retornando o erro "Module not found: Error: Cannot resolve module 'fs'".

Vi em algus fóruns que algumas soluções mas está confuso de como resolveria nesse caso. Vocês já passaram por isso?

**Comment by bassarisse** [comment]
Uma vez que a app-up-build não faz nada em runtime, mas apenas durante a "compilação" e empacotamento dos arquivos, não faço ideia de como ela pode estar afetando o @google-cloud/translate.

De qualquer forma, me parece que o problema seja o uso dessa lib no front-end ao invés do back, o que não parece ser suportado, ou seja, ela deve ser usada via Node.js, e não via navegador.

**Comment by paul8liveira** [comment]
Está certo, obrigado pelo retorno. 
Realmente não há maneira de resolver, mas como solução, ao invés de utilizar o pacote, consumi a API pela URL.
